org: drewjwyatt
app: visualping-messenger
service: to-mms

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  to-mms:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /hello
          method: GET
