org: drewjwyatt
app: visualping-messenger
service: visualping

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

functions:
  to-mms:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /to-mms
          method: POST
